[chore] 테스트용 로그 제거 및 배포용에 맞게 일부 수정

diff --git a/.github/workflows/ci-cd.yml b/.github/workflows/ci-cd.yml
--- a/.github/workflows/ci-cd.yml
+++ b/.github/workflows/ci-cd.yml
@@ -144,6 +144,7 @@ jobs:
 
       - name: Deploy to EC2 via SSM
         run: |
+          # COMMAND_ID 저장
           COMMAND_ID=$(aws ssm send-command \
             --targets "Key=tag:App,Values=ktb-spring-01" \
             --document-name "AWS-RunShellScript" \
@@ -157,19 +158,19 @@ jobs:
             }' \
             --query "Command.CommandId" \
             --output text)
-          
-          echo "SSM Command ID: $COMMAND_ID"
-          
-          # 상태 polling
+                    
+          # COMMAND_ID의 Status 폴링
           STATUS="InProgress"
-          while [ "$STATUS" == "InProgress" ] || [ "$STATUS" == "Pending" ]; do
-            echo "Waiting for SSM command to finish...";
+          while [ "$STATUS" = "InProgress" ] || [ "$STATUS" = "Pending" ]; do
             sleep 3
             STATUS=$(aws ssm list-command-invocations --command-id "$COMMAND_ID" --details --query "CommandInvocations[0].Status" --output text)
-            echo "Status: $STATUS";
           done
           
-          # 로그 출력
-          aws ssm get-command-invocation \
-            --command-id "$COMMAND_ID" \
-            --instance-id $(aws ec2 describe-instances --filters "Name=tag:App,Values=ktb-spring-01" --query "Reservations[].Instances[].InstanceId" --output text)
+          echo "Deployment Status: $STATUS"
+          
+          if [ "$STATUS" = "Success" ]; then
+            echo "🎉 Deployment Success"
+          else
+            echo "❌ Deployment Failed. Check logs"
+            exit 1
+          fi
